---
- name: Install and manage Docker
  hosts: centos
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.yum:
        name: docker
        state: present

    - name: Ensure Docker service is started and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
