galaxy_info:
  author: Swapnil Jain
  description: Ansible role to install Docker CE on RHEL/CentOS/AlmaLinux/Rocky Linux
  company: Pisces Solutions Private Limited

  license: GPLv2

  min_ansible_version: "2.12"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - docker
    - containers

dependencies: []
